
package vgc_frankperez_17195;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class student_attendance extends javax.swing.JFrame {
DefaultTableModel model;

    public student_attendance() {
        initComponents();
        Atterase();
        Attshow_data("");
        Attdeactivate();
    }

    void Atterase(){
    text_Attstud.setText("");
    text_Attcourse.setText("");
    text_Attperc.setText("");
    }
 
     void Attshow_data(String value){
    String [] heads = {"sac","Student ID","Course code", "Perc of Attend"};
    String [] registers = new String [4];
    String sql = "select * from student_attendance where CONCAT (idstudent,' ',CourseNumb) LIKE '%" + value +"%'"  ;
    
    model = new DefaultTableModel(null,heads);
    
    vgc_students cc = new vgc_students();
    Connection cn = cc.conexion();
    
    Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()){
            registers[0]=rs.getString("sac");
            registers[1]=rs.getString("idstudent");
            registers[2]=rs.getString("CourseNumb");
            registers[3]=rs.getString("PercentageOfAttend");

            model.addRow(registers);
            }
            Att_Table.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
     
 void Attdeactivate(){
    text_Attstud.setEnabled(false);
    text_Attcourse.setEnabled(false);
    text_Attperc.setEnabled(false);
    Att_NewButton.setEnabled(true);
    Att_SaveButton.setEnabled(false);
    Att_CancelButton.setEnabled(false);
    }    
    
   void Attactivate(){
    text_Attstud.setEnabled(true);
    text_Attcourse.setEnabled(true); 
    text_Attperc.setEnabled(true);
    Att_NewButton.setEnabled(true);
    Att_SaveButton.setEnabled(true);
    Att_CancelButton.setEnabled(true);
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        text_Attcourse = new javax.swing.JTextField();
        text_Attstud = new javax.swing.JTextField();
        text_Attperc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Att_NewButton = new javax.swing.JButton();
        Att_SaveButton = new javax.swing.JButton();
        Att_CancelButton = new javax.swing.JButton();
        Att_ExitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Att_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Student's Attendance");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Student ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Course Code");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("% of Attendance");

        Att_NewButton.setText("New");
        Att_NewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Att_NewButtonActionPerformed(evt);
            }
        });

        Att_SaveButton.setText("Save");
        Att_SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Att_SaveButtonActionPerformed(evt);
            }
        });

        Att_CancelButton.setText("Cancel");
        Att_CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Att_CancelButtonActionPerformed(evt);
            }
        });

        Att_ExitButton.setText("Exit");
        Att_ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Att_ExitButtonActionPerformed(evt);
            }
        });

        Att_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Att_Table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(text_Attcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_Attstud, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_Attperc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Att_NewButton)
                                .addGap(18, 18, 18)
                                .addComponent(Att_SaveButton)
                                .addGap(18, 18, 18)
                                .addComponent(Att_CancelButton)
                                .addGap(18, 18, 18)
                                .addComponent(Att_ExitButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_Attstud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_Attcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_Attperc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Att_ExitButton)
                    .addComponent(Att_CancelButton)
                    .addComponent(Att_SaveButton)
                    .addComponent(Att_NewButton))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Att_NewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Att_NewButtonActionPerformed
    Atterase();
    Attactivate();        // TODO add your handling code here:
    }//GEN-LAST:event_Att_NewButtonActionPerformed

    private void Att_CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Att_CancelButtonActionPerformed
    Atterase();
    Attdeactivate();        // TODO add your handling code here:
    }//GEN-LAST:event_Att_CancelButtonActionPerformed

    private void Att_ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Att_ExitButtonActionPerformed
    this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_Att_ExitButtonActionPerformed

    private void Att_SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Att_SaveButtonActionPerformed
   vgc_students cc = new vgc_students();
   Connection cn = cc.conexion();  
   
      String stud_numb, course_numb, perc_numb ;
   String sql="";
   stud_numb = text_Attstud.getText();
   course_numb = text_Attcourse.getText();
   perc_numb = text_Attperc.getText();
 
sql = "INSERT INTO student_attendance (idstudent, CourseNumb,PercentageOfAttend) VALUES (?,?,?)";
 
       try {
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, stud_numb);
            pst.setString(2, course_numb);
            pst.setString(3, perc_numb);

           int n= pst.executeUpdate();
   if(n>0){
           JOptionPane.showMessageDialog(null, "Data Saved");
           Attactivate();
           Attshow_data("");
           }
            
        } catch (SQLException ex) {
            Logger.getLogger(students.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Att_SaveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Att_CancelButton;
    private javax.swing.JButton Att_ExitButton;
    private javax.swing.JButton Att_NewButton;
    private javax.swing.JButton Att_SaveButton;
    private javax.swing.JTable Att_Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField text_Attcourse;
    private javax.swing.JTextField text_Attperc;
    private javax.swing.JTextField text_Attstud;
    // End of variables declaration//GEN-END:variables
}
